services:
  backend:
    build: ./backend
    container_name: catalog_backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@catalog_db:5432/catalog_db?sslmode=disable
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

    depends_on:
      - db

  frontend:
    build: ./catalogue
    container_name: catalog_frontend
    working_dir: /app
    volumes:
      - ./catalogue:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

volumes:
  postgres_data:
